[tool.robotpy]

robotpy_version = "2026.1.1"

components = [
    "commands2",
    "pathplannerlib"
]

# Other pip packages to install
requires = [
    "robotpy-pykit>=1.0.1",
    "robotpy-opencv; platform_machine == 'roborio'",
    "opencv-python; platform_machine != 'roborio'"
]
