[tool.robotpy]

robotpy_version = "2026.2.1"

components = [
    "apriltag",
    "commands2"
]

# Other pip packages to install
requires = [
    "phoenix6",
    "robotpy-pathplannerlib",
    "robotpy-pykit"
]
